# Generated by Django 2.0.2 on 2019-05-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('roomNo', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('student_name', models.CharField(default='', max_length=255)),
                ('student_id', models.CharField(default='', max_length=255)),
                ('username', models.CharField(default='', max_length=255)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('final_hostel', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
            ],
            options={
                'verbose_name': 'FinalPreference',
                'verbose_name_plural': 'FinalPreference',
            },
        ),
        migrations.CreateModel(
            name='MessFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribedHostelName', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('baseHostelName', models.CharField(blank=True, choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], default='', max_length=255)),
                ('roomNo', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('username', models.CharField(max_length=255)),
                ('cleanliness_hygiene', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('qual_breakfast', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('qual_lunch', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('qual_dinner', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('catering_punctuality', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], null=True)),
                ('filled', models.BooleanField(default=False)),
                ('month', models.IntegerField(default=4)),
                ('year', models.IntegerField(default=2019)),
                ('comment', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'MessFeedback',
                'verbose_name_plural': 'MessFeedback',
            },
        ),
        migrations.CreateModel(
            name='Opi_calculated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('opi_value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numberOfFeedback', models.IntegerField(default=0)),
                ('numberOfSubscriptions', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=4)),
                ('year', models.IntegerField(default=2019)),
                ('cleanliness_av', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('breakfast_quality_av', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('lunch_quality_av', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('dinner_quality_av', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('catering_av', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('raw_materials_quality', models.IntegerField(choices=[(0, 'Worst'), (1, 'Very Poor'), (2, 'Poor'), (3, 'Average'), (4, 'Good'), (5, 'Very Good')], default=0, null=True)),
            ],
            options={
                'verbose_name': 'Opi_calculated',
                'verbose_name_plural': 'Opi_calculated',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostelName', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('roomNo', models.CharField(blank=True, default='', max_length=225, null=True)),
                ('student_id', models.CharField(blank=True, max_length=225, null=True)),
                ('student_name', models.CharField(blank=True, max_length=225, null=True)),
                ('latest_submission_time', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('month', models.IntegerField(default=6)),
                ('year', models.IntegerField(default=2019)),
                ('h1', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('h2', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
                ('h3', models.CharField(choices=[('Barak', 'Barak'), ('Bramhaputra', 'Bramhaputra'), ('Dhansiri', 'Dhansiri'), ('Dibang', 'Dibang'), ('Dihing', 'Dihing'), ('Kameng', 'Kameng'), ('Kapili', 'Kapili'), ('Lohit', 'Lohit'), ('Manas', 'Manas'), ('Siang', 'Siang'), ('Subansiri', 'Subansiri'), ('Umiam', 'Umiam'), ('NA', 'NA')], max_length=255)),
            ],
            options={
                'verbose_name': 'Preferences',
                'verbose_name_plural': 'Preferences',
            },
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together={('username', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='opi_calculated',
            unique_together={('hostelName', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='messfeedback',
            unique_together={('username', 'month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='finalpreference',
            unique_together={('username', 'month', 'year')},
        ),
    ]
